import type { Hero } from '../../../features/heroes/types/hero.types'
import type { Favorite } from '../../../features/heroes/types/favorite.types'

export const initialHeroes: Hero[] = [
  {
    id: 'hero-001',
    name: 'Solar Sentinel',
    slug: 'solar-sentinel',
    alterEgo: 'Maya Cross',
    publisher: 'Other',
    alignment: 'hero',
    status: 'active',
    firstAppearance: 'Solar Sentinel #1',
    team: 'Aurora Guard',
    characters: 'Maya Cross',
    description: 'Manipula energia solar y crea escudos luminicos.',
    powers: ['Fotones', 'Escudos', 'Vuelo'],
    stats: {
      strength: 78,
      intelligence: 82,
      speed: 74,
      durability: 80,
    },
    imageUrl: '/images/heroes/hero-001.svg',
    createdAt: '2025-12-01T10:00:00.000Z',
    updatedAt: '2025-12-01T10:00:00.000Z',
  },
  {
    id: 'hero-002',
    name: 'Nightwave',
    slug: 'nightwave',
    alterEgo: 'Theo Ward',
    publisher: 'DC',
    alignment: 'hero',
    status: 'active',
    firstAppearance: 'Nightwave: Origin',
    team: 'Vigilantes',
    characters: 'Theo Ward',
    description: 'Detective urbano con gadgets sonicos y sigilo total.',
    powers: ['Sigilo', 'Tecnologia', 'Combate'],
    stats: {
      strength: 62,
      intelligence: 88,
      speed: 70,
      durability: 68,
    },
    imageUrl: '/images/heroes/hero-002.svg',
    createdAt: '2025-12-02T10:00:00.000Z',
    updatedAt: '2025-12-02T10:00:00.000Z',
  },
  {
    id: 'hero-003',
    name: 'Crimson Arc',
    slug: 'crimson-arc',
    alterEgo: 'Avery Nolan',
    publisher: 'Marvel',
    alignment: 'hero',
    status: 'active',
    firstAppearance: 'Crimson Arc #7',
    team: 'Nova Unit',
    characters: 'Avery Nolan',
    description: 'Domina portales cortos para combate y rescate.',
    powers: ['Portales', 'Energia', 'Rescate'],
    stats: {
      strength: 72,
      intelligence: 76,
      speed: 84,
      durability: 73,
    },
    imageUrl: '/images/heroes/hero-003.svg',
    createdAt: '2025-12-03T10:00:00.000Z',
    updatedAt: '2025-12-03T10:00:00.000Z',
  },
  {
    id: 'hero-004',
    name: 'Atlas Frame',
    slug: 'atlas-frame',
    alterEgo: 'Kai Benton',
    publisher: 'Image',
    alignment: 'hero',
    status: 'active',
    firstAppearance: 'Atlas Frame #12',
    team: 'Helios Division',
    characters: 'Kai Benton',
    description: 'Exotraje pesado con modulos tacticos intercambiables.',
    powers: ['Exotraje', 'Artilleria', 'Defensa'],
    stats: {
      strength: 90,
      intelligence: 64,
      speed: 52,
      durability: 92,
    },
    imageUrl: '/images/heroes/hero-004.svg',
    createdAt: '2025-12-04T10:00:00.000Z',
    updatedAt: '2025-12-04T10:00:00.000Z',
  },
  {
    id: 'hero-005',
    name: 'Glacier Rose',
    slug: 'glacier-rose',
    alterEgo: 'Lina Vale',
    publisher: 'Other',
    alignment: 'hero',
    status: 'active',
    firstAppearance: 'Frozen Bloom #3',
    team: 'Aurora Guard',
    characters: 'Lina Vale',
    description: 'Controla hielo y niebla para inmovilizar enemigos.',
    powers: ['Hielo', 'Niebla', 'Control'],
    stats: {
      strength: 66,
      intelligence: 79,
      speed: 60,
      durability: 72,
    },
    imageUrl: '/images/heroes/hero-005.svg',
    createdAt: '2025-12-05T10:00:00.000Z',
    updatedAt: '2025-12-05T10:00:00.000Z',
  },
  {
    id: 'hero-006',
    name: 'Circuit Fox',
    slug: 'circuit-fox',
    alterEgo: 'Noa Vega',
    publisher: 'Marvel',
    alignment: 'villain',
    status: 'active',
    firstAppearance: 'Circuit Fox #2',
    team: 'Null Syndicate',
    characters: 'Noa Vega',
    description: 'Velocidad extrema y hackeo de sistemas industriales.',
    powers: ['Velocidad', 'Hackeo', 'Sabotaje'],
    stats: {
      strength: 58,
      intelligence: 90,
      speed: 92,
      durability: 60,
    },
    imageUrl: '/images/heroes/hero-006.svg',
    createdAt: '2025-12-06T10:00:00.000Z',
    updatedAt: '2025-12-06T10:00:00.000Z',
  },
]

export const initialFavorites: Favorite[] = []
